FROM python:3.8.5-alpine3.12

RUN apk add --no-cache bash
# bcrypt python package dependecies
RUN apk add build-base
RUN apk add --update musl-dev gcc libffi-dev

RUN mkdir /app
WORKDIR /app

RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

ENTRYPOINT celery -A background_app worker --concurrency=5 --loglevel=DEBUG